# Generated by Django 3.1.5 on 2021-04-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('moduleCredits', models.IntegerField()),
                ('nEnrolled', models.IntegerField()),
                ('assesmentMethod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mCourseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Deadline', models.CharField(max_length=25)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mcourse')),
            ],
        ),
        migrations.CreateModel(
            name='mCourseLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, unique=True)),
                ('TutorContact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='mEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mcourse')),
            ],
        ),
        migrations.CreateModel(
            name='mMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attainment', models.CharField(max_length=50)),
                ('Assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mcourse')),
            ],
        ),
        migrations.CreateModel(
            name='mStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Deadlines',
        ),
        migrations.AddField(
            model_name='mmarks',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mstudents'),
        ),
        migrations.AddField(
            model_name='menrollment',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mstudents'),
        ),
        migrations.AddField(
            model_name='mcourse',
            name='Leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mcourseleaders'),
        ),
    ]
