# Generated by Django 3.1.5 on 2021-03-07 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='DateDue',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 17, 51, 55, 14455), verbose_name='Due date'),
        ),
    ]
