# Generated by Django 3.1.5 on 2021-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210413_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcourse',
            name='moduleCredits',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mcourse',
            name='nEnrolled',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mcourseleaders',
            name='TutorContact',
            field=models.CharField(max_length=25),
        ),
    ]
